### ISSUE TITLE
Await is only valid in async function

### ISSUE THREAD

**Issue by darrylmorley** [compwright/axios-oauth-client#11]
Hi,

I'm having an issue with async?

```
const axios = require("axios");
const oauth = require("axios-oauth-client");

const getRefreshToken = oauth.client(axios.create(), {
  url: "refresh_token_url",
  grant_type: "refresh_token",
  client_id: "client_id",
  client_secret:
    "client_secret",
  refresh_token: "refresh_token",
  scope: "employee:all"
});

try {
  const auth = await getRefreshToken();
  console.log(auth);
} catch (error) {
  console.error(error);
}
```
I get:
```
SyntaxError: await is only valid in async function
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by compwright** [comment]
That's not an issue with this library, it's an issue with trying to run async/await code without the async part.

Please research the error you're getting on Google, the answer is readily available there. Thanks!
